---
title: "NIOSH and FDA Webscraping"
author: "Nikhil Kalathil"
date: "4/13/2021"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document will contain a program to webscrap and format FDA EUA approvals. 

```{r, include = FALSE}
library(tidyverse)
library(rvest)
library(rebus)
library(lubridate)
library(here)
library(ggthemes)
```

```{r}

box_dir <- "C:/Users/Nikhil Kalathil/Box/COVID 19 Master Folder/Data/Masks/FDA/"

```

```{r}
box_here <- function(file) {
  paste(box_dir, file, sep = "")
}
```

# FDA EUA 

```{r}
fda <- "https://www.fda.gov/medical-devices/coronavirus-disease-2019-covid-19-emergency-use-authorizations-medical-devices/personal-protective-equipment-euas"
```

```{r}
fda_html <- read_html(fda)
```

```{r}
fda_tables <- fda_html %>% html_table()
```

```{r}
surgical_eua <- fda_tables[[1]] 
```

```{r}
removed_surgical <- fda_tables[[2]]
```


```{r}
fda_eua <- surgical_eua %>%
  select(company = Manufacturer, 
         date_added = `Date of Addition`, 
         product = `Authorized Product Name (including model numbers)`)

fda_eua <- removed_surgical %>% 
  select(company = Manufacturer, 
         date_removed = `Date No
			Longer
			Authorized`, 
			product = `Surgical Mask Model(s) No Longer Authorized`) %>% 
  bind_rows(fda_eua)
```

```{r}
saveRDS(fda_eua, box_here("fda_eua.RDS"))
```


```{r}
china_non_niosh <- fda_tables[[4]]
```

```{r}
china_removed <- fda_tables[[5]]
```

```{r}
imported_ffp <- fda_tables[[6]]
```

```{r}
other_bio <- fda_tables[[7]]
```

# FDA 510K (OLD AND UNNECESSARY)

We can download the FDA510K database from 1996 to current and read that file. In addition, we can scrape FDA510 applications from 2017 to present. We present cleaning procedures for both. 

```{r}
fda_510_html <- read_html("https://www.fda.gov/medical-devices/510k-clearances/february-2019-510k-clearances")
```

```{r}
test <- fda_510_html %>% html_nodes(".col-md-8.col-md-push-2") 
```

```{r}
test1 <- test %>% html_text(trim = TRUE) %>% strsplit("DEVICE:") 

test2 <- as.data.frame(test1[[1]])

colnames(test2) <- c("full_desc")
```

```{r}
test3 <- test2 %>% 
  separate(full_desc, into = c("device_company", "other"), sep = "510") %>% 
  separate(device_company, into = c("device", "company"), sep = "\n") %>% 
  separate(other, into = c("info", "date"), sep = "SE DECISION MADE:") %>% 
  separate(date, into = c("date", "other"), sep = "\n")
```

```{r}
dates <- seq.Date(from = as.Date("2017-01-01"), to = as.Date("2021-04-01"), by = "month")
dates <- str_replace(tolower(as.character(format(dates, "%B %Y"))), " ", "-")
```

```{r}
urls <- paste0("https://www.fda.gov/medical-devices/510k-clearances/", dates, "-510k-clearances")
```

```{r}
table_510_month <- function(html) {
  
  raw_html <- read_html(html) %>% 
    html_nodes(".col-md-8.col-md-push-2") %>% 
    html_text(trim = TRUE) %>% 
    strsplit("DEVICE:") 

  html_df <- as.data.frame(raw_html[[1]])

  colnames(html_df) <- c("full_desc")

  table_510 <- html_df %>% 
    separate(full_desc, into = c("device_company", "other"), sep = "510") %>% 
    separate(device_company, into = c("device", "company"), sep = "\n") %>% 
    separate(other, into = c("info", "date"), sep = "SE DECISION MADE:") %>% 
    separate(date, into = c("date", "other"), sep = "\n") %>% 
    filter(str_detect(device, fixed("mask", ignore_case = TRUE)) |
           str_detect(device, fixed("respirator", ignore_case = TRUE)) | 
           str_detect(device, fixed("filtering", ignore_case = TRUE)) | 
             str_detect(device, fixed("ventilator", ignore_case = TRUE)))
  
  return(table_510)
  
    
}
```

```{r}
rec_510K <- urls %>% 
  map_df(table_510_month)
```

